//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioDuplicateFinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioDuplicateFinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudioDuplicateFinder.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        public static string ContentGridPageTitle {
            get {
                return ResourceManager.GetString("ContentGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files for deletion (or move) based on user custom settings #1.
        /// </summary>
        public static string Custom1 {
            get {
                return ResourceManager.GetString("Custom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files for deletion (or move) based on user custom settings #2.
        /// </summary>
        public static string Custom2 {
            get {
                return ResourceManager.GetString("Custom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files for deletion (or move) based on user custom settings #3.
        /// </summary>
        public static string Custom3 {
            get {
                return ResourceManager.GetString("Custom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Groups.
        /// </summary>
        public static string DuplicateGroupsPageTitle {
            get {
                return ResourceManager.GetString("DuplicateGroupsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate List.
        /// </summary>
        public static string DuplicateListPageTitle {
            get {
                return ResourceManager.GetString("DuplicateListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcludedDirectories.
        /// </summary>
        public static string ExcludedDirectories {
            get {
                return ResourceManager.GetString("ExcludedDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FolderMinus_48 {
            get {
                object obj = ResourceManager.GetObject("FolderMinus_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FolderMinus_Red_48 {
            get {
                object obj = ResourceManager.GetObject("FolderMinus_Red_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FolderPlus_48 {
            get {
                object obj = ResourceManager.GetObject("FolderPlus_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FolderPlus_Red_48 {
            get {
                object obj = ResourceManager.GetObject("FolderPlus_Red_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FolderRedo_48 {
            get {
                object obj = ResourceManager.GetObject("FolderRedo_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included Directories.
        /// </summary>
        public static string IncludedDirectories {
            get {
                return ResourceManager.GetString("IncludedDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string ListDetailsListDescription {
            get {
                return ResourceManager.GetString("ListDetailsListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetails.
        /// </summary>
        public static string ListDetailsPageTitle {
            get {
                return ResourceManager.GetString("ListDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveFiles.
        /// </summary>
        public static string MoveFiles {
            get {
                return ResourceManager.GetString("MoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Play_48 {
            get {
                object obj = ResourceManager.GetObject("Play_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle.
        /// </summary>
        public static string Recycle {
            get {
                return ResourceManager.GetString("Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reset_48 {
            get {
                object obj = ResourceManager.GetObject("Reset_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application finds duplicate audio files even if the files are in different formats or configurations..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About AudioDuplicateFinder.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudioDuplicateFinder Home Page.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string ShellMenuFileHeader {
            get {
                return ResourceManager.GetString("ShellMenuFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string ShellMenuItemFileExitHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string ShellMenuItemFileSettingsPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileSettingsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI Settings.
        /// </summary>
        public static string ShellMenuItemFileSettingsPageHeaderTooltip {
            get {
                return ResourceManager.GetString("ShellMenuItemFileSettingsPageHeaderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        public static string ShellMenuItemViewsContentGridPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsContentGridPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Groups.
        /// </summary>
        public static string ShellMenuItemViewsDuplicateGroupsPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsDuplicateGroupsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate List.
        /// </summary>
        public static string ShellMenuItemViewsDuplicateListPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsDuplicateListPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetails.
        /// </summary>
        public static string ShellMenuItemViewsListDetailsPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsListDetailsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMenuItemViewsMainPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsMainPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView.
        /// </summary>
        public static string ShellMenuItemViewsWebViewPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsWebViewPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMenuMain {
            get {
                return ResourceManager.GetString("ShellMenuMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display main view.
        /// </summary>
        public static string ShellMenuMain_ToolTip {
            get {
                return ResourceManager.GetString("ShellMenuMain_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select.
        /// </summary>
        public static string ShellMenuSelect_Header {
            get {
                return ResourceManager.GetString("ShellMenuSelect_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto select files for deletion ( or move) based on selected criteria.
        /// </summary>
        public static string ShellMenuSelect_Header_ToolTip {
            get {
                return ResourceManager.GetString("ShellMenuSelect_Header_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Selection.
        /// </summary>
        public static string ShellMenuSelectCustomSelection {
            get {
                return ResourceManager.GetString("ShellMenuSelectCustomSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a custom selection setting.
        /// </summary>
        public static string ShellMenuSelectCustomSelection_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectCustomSelection_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select order of precedence for resolution, file size, time duration, file name length..
        /// </summary>
        public static string ShellMenuSelectCustomSelection_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectCustomSelection_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also select if greater than or less than for each precedence..
        /// </summary>
        public static string ShellMenuSelectCustomSelection_ToolTip3 {
            get {
                return ResourceManager.GetString("ShellMenuSelectCustomSelection_ToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Highest Resolution.
        /// </summary>
        public static string ShellMenuSelectHighestResolution {
            get {
                return ResourceManager.GetString("ShellMenuSelectHighestResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicate files with the highest resolultion for deletion (or move)..
        /// </summary>
        public static string ShellMenuSelectHighestResolution_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectHighestResolution_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files with the lowest resolution..
        /// </summary>
        public static string ShellMenuSelectHighestResolution_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectHighestResolution_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Largest File Size.
        /// </summary>
        public static string ShellMenuSelectLargeFileSize {
            get {
                return ResourceManager.GetString("ShellMenuSelectLargeFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicate files with the largest file size for deletion (or move)..
        /// </summary>
        public static string ShellMenuSelectLargeFileSize_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLargeFileSize_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files with the smallest file size..
        /// </summary>
        public static string ShellMenuSelectLargeFileSize_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLargeFileSize_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Longest Duration.
        /// </summary>
        public static string ShellMenuSelectLongestDuration {
            get {
                return ResourceManager.GetString("ShellMenuSelectLongestDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicate files with the longest duration for deletion (or move)..
        /// </summary>
        public static string ShellMenuSelectLongestDuration_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLongestDuration_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files with the shortest time (duration)..
        /// </summary>
        public static string ShellMenuSelectLongestDuration_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLongestDuration_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Longest File Name.
        /// </summary>
        public static string ShellMenuSelectLongestFileName {
            get {
                return ResourceManager.GetString("ShellMenuSelectLongestFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicate files with the longest file names for deletion (or move)..
        /// </summary>
        public static string ShellMenuSelectLongestFileName_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLongestFileName_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files with the shortest file name..
        /// </summary>
        public static string ShellMenuSelectLongestFileName_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLongestFileName_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Lowest Resolution.
        /// </summary>
        public static string ShellMenuSelectLowestResolution {
            get {
                return ResourceManager.GetString("ShellMenuSelectLowestResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicate files with the lowest resolultion for deletion (or move).
        /// </summary>
        public static string ShellMenuSelectLowestResolution_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLowestResolution_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files with the highest resolution..
        /// </summary>
        public static string ShellMenuSelectLowestResolution_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLowestResolution_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select lowest resolution, shortest duration, and shortest name.
        /// </summary>
        public static string ShellMenuSelectLowResShrtTimeShrtName {
            get {
                return ResourceManager.GetString("ShellMenuSelectLowResShrtTimeShrtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicate files with the lowest resolultion, shortest time, and shorter file name for deletion (or move)..
        /// </summary>
        public static string ShellMenuSelectLowResShrtTimeShrtName_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLowResShrtTimeShrtName_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files with the highest resolution, longest time, and longer file name..
        /// </summary>
        public static string ShellMenuSelectLowResShrtTimeShrtName_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLowResShrtTimeShrtName_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution has highest precedence and duration is only considered if same resolution..
        /// </summary>
        public static string ShellMenuSelectLowResShrtTimeShrtName_ToolTip3 {
            get {
                return ResourceManager.GetString("ShellMenuSelectLowResShrtTimeShrtName_ToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Shortest Duration.
        /// </summary>
        public static string ShellMenuSelectShortDuration {
            get {
                return ResourceManager.GetString("ShellMenuSelectShortDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicate files with the shortest duration for deletion (or move)..
        /// </summary>
        public static string ShellMenuSelectShortDuration_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectShortDuration_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files with the longest time (duration)..
        /// </summary>
        public static string ShellMenuSelectShortDuration_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectShortDuration_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Shortest File Name.
        /// </summary>
        public static string ShellMenuSelectShortestFileName {
            get {
                return ResourceManager.GetString("ShellMenuSelectShortestFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicate files with the shortest file names for deletion (or move)..
        /// </summary>
        public static string ShellMenuSelectShortestFileName_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectShortestFileName_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files with the longest file name..
        /// </summary>
        public static string ShellMenuSelectShortestFileName_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectShortestFileName_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shortest duration, lowest resolution, and shortest name.
        /// </summary>
        public static string ShellMenuSelectShrtTimeLowResShrtName {
            get {
                return ResourceManager.GetString("ShellMenuSelectShrtTimeLowResShrtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicate files with the shortest time, lowest resolultion, and shorter file name for deletion (or move)..
        /// </summary>
        public static string ShellMenuSelectShrtTimeLowResShrtName_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectShrtTimeLowResShrtName_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files with the longest time, highest resolution, and longer file name..
        /// </summary>
        public static string ShellMenuSelectShrtTimeLowResShrtName_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectShrtTimeLowResShrtName_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration length has highest precedence and resolution is only considered if same time length..
        /// </summary>
        public static string ShellMenuSelectShrtTimeLowResShrtName_ToolTip3 {
            get {
                return ResourceManager.GetString("ShellMenuSelectShrtTimeLowResShrtName_ToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Smallest File Size.
        /// </summary>
        public static string ShellMenuSelectSmallFileSize {
            get {
                return ResourceManager.GetString("ShellMenuSelectSmallFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicate files with the smallest file size for deletion (or move)..
        /// </summary>
        public static string ShellMenuSelectSmallFileSize_ToolTip1 {
            get {
                return ResourceManager.GetString("ShellMenuSelectSmallFileSize_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files with the largest file size..
        /// </summary>
        public static string ShellMenuSelectSmallFileSize_ToolTip2 {
            get {
                return ResourceManager.GetString("ShellMenuSelectSmallFileSize_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Views.
        /// </summary>
        public static string ShellMenuViewsHeader {
            get {
                return ResourceManager.GetString("ShellMenuViewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Scan.
        /// </summary>
        public static string StartScan {
            get {
                return ResourceManager.GetString("StartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StopButton {
            get {
                object obj = ResourceManager.GetObject("StopButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back (Alt + Left).
        /// </summary>
        public static string WebViewPageBackButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageBackButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page failed to load. Check connection and retry..
        /// </summary>
        public static string WebViewPageFaildedMessage {
            get {
                return ResourceManager.GetString("WebViewPageFaildedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward (Alt + Right).
        /// </summary>
        public static string WebViewPageForwardButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageForwardButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string WebViewPageLoadingText {
            get {
                return ResourceManager.GetString("WebViewPageLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser (Ctrl + T).
        /// </summary>
        public static string WebViewPageOpenInBrowserButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageOpenInBrowserButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh (F5).
        /// </summary>
        public static string WebViewPageRefreshButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageRefreshButtonTooltip", resourceCulture);
            }
        }
    }
}
